import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  quickview,
}: Readonly<{
  children: React.ReactNode;
  pokemon: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div id="modal-root" />
        {quickview}
        {children}
      </body>
    </html>
  );
}
