on:
  release:
    types: [published]

name: Deploy to Production

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.SSH_KEY }}
      - name: Force push SHA to Production branch
        run: |
          echo "${{ secrets.SSH_KEY }}"
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          echo "${GITHUB_SHA}"
          git push --force origin ${GITHUB_SHA}:production
