on:
  release:
    types: [published]

name: Deploy to Production

permissions:
  contents: write
  pull-requests: write

jobs:
  create-deployment-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Create Deployment PR
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          RELEASE_VERSION="${{ github.event.release.tag_name }}"
          TARGET_COMMIT="${{ github.event.release.target_commitish }}"
          RELEASE_BODY="${{ github.event.release.body }}"
          
          TIMESTAMP=$(date +%Y%m%d-%H%M%S)
          BRANCH_NAME="deploy/$RELEASE_VERSION-$TIMESTAMP"
          
          git checkout production
          git pull origin production
          git checkout -b $BRANCH_NAME
          
          git reset --hard origin/$TARGET_COMMIT
          
          git push origin $BRANCH_NAME

      - name: Create Deployment PR
        env:
            GH_TOKEN: ${{ github.token }}
        run: |
          gh pr create \
            --title "release: $RELEASE_VERSION" \
            --body "## 🧑‍🚀 Production Deployment
          
          **Release:** $RELEASE_VERSION
          **Target:** $TARGET_COMMIT

          ## 📝 Release Notes
          
          $RELEASE_BODY

          ---
          
          ### ⚠️ This is an automated deployment PR. Please review and approve to deploy to production." \
            --base production \
            --head $BRANCH_NAME
